const { ensureAssets, fileSize } = require("./files");

function ist(day, hour, minute) {
  return new Date(Date.UTC(2026, 8, day, hour, minute) - 5.5 * 60 * 60 * 1000).toISOString();
}

function buildSeed(uploadsDir) {
  ensureAssets(uploadsDir);
  const size = (name) => fileSize(uploadsDir, name);

  const users = [
    { id: "u-saurav", name: "Saurav Raj", handle: "saurav", role: "Member", status: "online", title: "CSE, 3rd year", color: "#2F4A6E" },
    { id: "u-arjun", name: "Arjun Mehta", handle: "arjun", role: "Member", status: "online", title: "CSE, 2nd year", color: "#3E4C3A" },
    { id: "u-rahul", name: "Rahul Sharma", handle: "rahul", role: "Mentor", status: "online", title: "ICPC mentor", color: "#2E4A48" },
    { id: "u-priya", name: "Priya Singh", handle: "priya", role: "Mentor", status: "online", title: "Alumni mentor", color: "#4A3848" },
    { id: "u-aditya", name: "Aditya Verma", handle: "aditya", role: "Core Team", status: "online", title: "CP lead", color: "#3A4458" },
    { id: "u-ananya", name: "Ananya Gupta", handle: "ananya", role: "Problem Setter", status: "offline", title: "Internal contest setter", color: "#4A4532" },
    { id: "u-vikram", name: "Vikram Nair", handle: "vikram", role: "Volunteer", status: "online", title: "Workshop volunteer", color: "#3E3A55" },
    { id: "u-kavita", name: "Dr. Kavita Rao", handle: "kavita", role: "Faculty Coordinator", status: "offline", title: "Faculty coordinator", color: "#5A3E3E" },
    { id: "u-neha", name: "Neha Kapoor", handle: "neha", role: "Admin", status: "online", title: "Coding Hub admin", color: "#2C3E50" },
    { id: "u-ishaan", name: "Ishaan Patel", handle: "ishaan", role: "Manager", status: "offline", title: "Operations", color: "#3D4F3A" },
    { id: "u-karan", name: "Karan Malhotra", handle: "karan", role: "Member", status: "online", title: "CSE, 3rd year", color: "#34495E" },
    { id: "u-sneha", name: "Sneha Iyer", handle: "sneha", role: "Member", status: "online", title: "CSE, 2nd year", color: "#3F4A3A" },
    { id: "u-rohan", name: "Rohan Das", handle: "rohan", role: "Member", status: "offline", title: "ECE, 3rd year", color: "#4A4038" },
    { id: "u-meera", name: "Meera Krishnan", handle: "meera", role: "Member", status: "online", title: "CSE, 1st year", color: "#3A3F55" },
    { id: "u-tanvi", name: "Tanvi Shah", handle: "tanvi", role: "Member", status: "offline", title: "IT, 2nd year", color: "#4A3540" },
    { id: "u-harsh", name: "Harsh Vardhan", handle: "harsh", role: "Volunteer", status: "online", title: "Contest volunteer", color: "#2F4540" },
    { id: "u-devansh", name: "Devansh Jain", handle: "devansh", role: "Member", status: "online", title: "CSE, 4th year", color: "#3E4450" },
    { id: "u-pooja", name: "Pooja Reddy", handle: "pooja", role: "Member", status: "offline", title: "CSE, 3rd year", color: "#453E32" },
    { id: "u-nikhil", name: "Nikhil Rao", handle: "nikhil", role: "Problem Setter", status: "online", title: "Setter", color: "#323E4A" },
    { id: "u-aisha", name: "Aisha Khan", handle: "aisha", role: "Member", status: "online", title: "CSE, 2nd year", color: "#4A3A45" },
    { id: "u-varun", name: "Varun Bhatia", handle: "varun", role: "Member", status: "offline", title: "CSE, 3rd year", color: "#2E4038" },
    { id: "u-sanya", name: "Sanya Kapoor", handle: "sanya", role: "Member", status: "online", title: "IT, 3rd year", color: "#3A3A4A" },
  ];

  const channels = [
    { id: "ch-announcements", name: "announcements", category: "General", description: "Important Coding Hub announcements.", topic: "Official updates for the community" },
    { id: "ch-general", name: "general", category: "General", description: "Off-topic and community conversation.", topic: "Campus life, projects, and everything around the lab" },
    { id: "ch-cp", name: "cp-general", category: "Competitive Programming", description: "General competitive programming conversation.", topic: "Practice, ratings, and platforms" },
    { id: "ch-doubts", name: "doubts", category: "Competitive Programming", description: "Students ask questions about problems, errors, and concepts.", topic: "Short questions and debugging help" },
    { id: "ch-problems", name: "problem-discussion", category: "Competitive Programming", description: "Discuss approaches, edge cases and editorials.", topic: "Detailed discussion of individual problems" },
    { id: "ch-contests", name: "contests", category: "Competitive Programming", description: "Upcoming contests, participation, and post-contest discussion.", topic: "What the hub is writing this week" },
    { id: "ch-icpc", name: "icpc", category: "Competitive Programming", description: "ICPC-specific discussions, team coordination, and preparation.", topic: "Regionals prep, rosters, and practice sets" },
    { id: "ch-resources", name: "resources", category: "Learning", description: "Useful PDFs, articles, cheatsheets, videos, and links.", topic: "Material worth keeping" },
    { id: "ch-workshops", name: "workshops", category: "Learning", description: "Workshop announcements, questions, and resources.", topic: "Labs, sessions, and follow-ups" },
  ];

  const conversations = [
    { id: "dm-rahul", type: "dm", name: null, participantIds: ["u-saurav", "u-rahul"] },
    { id: "dm-priya", type: "dm", name: null, participantIds: ["u-saurav", "u-priya"] },
    { id: "dm-aditya", type: "dm", name: null, participantIds: ["u-saurav", "u-aditya"] },
    { id: "grp-icpc", type: "group", name: "ICPC Team", participantIds: ["u-saurav", "u-arjun", "u-priya", "u-rahul", "u-aditya"] },
    {
      id: "grp-core",
      type: "group",
      name: "CP Core Team",
      participantIds: ["u-saurav", "u-aditya", "u-neha", "u-ishaan", "u-ananya", "u-rahul", "u-vikram", "u-priya"],
    },
  ];

  const base = {
    editedAt: null,
    deleted: false,
    isPinned: false,
    attachments: [],
    reactions: [],
    poll: null,
    problem: null,
    resource: null,
    parentId: null,
    channelId: null,
    conversationId: null,
  };

  const messages = [
    {
      ...base,
      id: "m-ann-icpc",
      channelId: "ch-announcements",
      authorId: "u-neha",
      createdAt: ist(27, 10, 0),
      isPinned: true,
      content: "ICPC team registration opens tomorrow at 10:00 AM. Regionals team of three, one laptop. The form is on the Coding Hub notice board. Deadline: Oct 4.",
    },
    {
      ...base,
      id: "m-ann-python",
      channelId: "ch-announcements",
      authorId: "u-kavita",
      createdAt: ist(29, 11, 5),
      isPinned: true,
      content: "Python workshop starts today at 5:00 PM in Lab 3. Bring a laptop with Python 3.11. Attendance is marked for volunteers as well.",
    },
    {
      ...base,
      id: "m-ann-saturday",
      channelId: "ch-announcements",
      authorId: "u-aditya",
      createdAt: ist(29, 14, 10),
      isPinned: true,
      content: "Weekly CP contest on Saturday, 8:00 PM. Codeforces-style, 6 problems, 2 hours. The ranklist will be posted in #contests.",
    },
    {
      ...base,
      id: "m-gen-lab",
      channelId: "ch-general",
      authorId: "u-karan",
      createdAt: ist(28, 16, 20),
      content: "Lab 3 projector is working again. If you are staying back for the contest, the lab assistant wants the lights off by 9.",
    },
    {
      ...base,
      id: "m-gen-project",
      channelId: "ch-general",
      authorId: "u-sneha",
      createdAt: ist(28, 16, 44),
      content: "Project night is Thursday, not Friday. We moved it so it does not collide with CodeChef Starters.",
      reactions: [{ emoji: "👍", userIds: ["u-saurav", "u-meera", "u-karan"] }],
    },
    {
      ...base,
      id: "m-gen-handbook",
      channelId: "ch-general",
      authorId: "u-meera",
      createdAt: ist(29, 18, 5),
      content: "Someone left a printed copy of the CP handbook in the lab. I put it back on the resources shelf.",
    },
    {
      ...base,
      id: "m-cp-rating",
      channelId: "ch-cp",
      authorId: "u-aditya",
      createdAt: ist(26, 21, 10),
      content: "Rating is a lagging indicator. If your last 10 rounds were all virtual, the graph will lie until you write a live contest.",
      reactions: [{ emoji: "💡", userIds: ["u-priya", "u-rahul", "u-sneha"] }],
    },
    {
      ...base,
      id: "m-cp-platforms",
      channelId: "ch-cp",
      authorId: "u-priya",
      createdAt: ist(27, 8, 40),
      content: "AtCoder beginner contests are kinder for implementation speed. Codeforces is still the one I want everyone writing on Saturday.",
    },
    {
      ...base,
      id: "m-cp-block",
      channelId: "ch-cp",
      authorId: "u-rahul",
      createdAt: ist(29, 17, 5),
      content: "Practice block this week: 45 minutes of upsolve, then 15 minutes writing down what actually failed. If you cannot name the mistake, post it in #doubts.",
      reactions: [{ emoji: "🔥", userIds: ["u-arjun", "u-aditya"] }],
    },
    {
      ...base,
      id: "m-doubt-seg",
      channelId: "ch-doubts",
      authorId: "u-rohan",
      createdAt: ist(29, 15, 12),
      content: "Segment tree update is fine on the sample and TLE on the full test. n is 2e5 and I am allocating the tree inside the test loop. Is that enough to explain it, or is the merge also too heavy?",
      attachments: [
        {
          id: "a-wa",
          name: "wa-pretest2.png",
          mime: "image/png",
          size: size("wa-pretest2.png"),
          url: "/uploads/wa-pretest2.png",
          kind: "image",
        },
      ],
      reactions: [{ emoji: "💡", userIds: ["u-priya"] }],
    },
    {
      ...base,
      id: "m-doubt-overflow",
      channelId: "ch-doubts",
      authorId: "u-arjun",
      createdAt: ist(29, 18, 20),
      content: "@saurav your binary search on the CodeChef problem overflows when n = 1e18 and low is a 32-bit int. I left a note next to the check function.",
      reactions: [{ emoji: "👍", userIds: ["u-sneha"] }],
    },
    {
      ...base,
      id: "m-doubt-mod",
      channelId: "ch-doubts",
      authorId: "u-tanvi",
      createdAt: ist(29, 18, 48),
      content: "How are people computing modular inverse when the mod is not prime? Fermat is what I know, and the problem statement only says the modulus is 1e9+7 for the first test file.",
    },
    {
      ...base,
      id: "m-prob-bs",
      channelId: "ch-problems",
      authorId: "u-arjun",
      createdAt: ist(24, 19, 12),
      content: "For minimum-maximum problems, binary search on answer is usually cleaner than a greedy scan. The check function has to be monotone or the whole thing is fiction.",
      reactions: [
        { emoji: "💡", userIds: ["u-priya", "u-rahul", "u-sneha", "u-karan"] },
        { emoji: "👍", userIds: ["u-aditya", "u-meera"] },
      ],
    },
    {
      ...base,
      id: "m-prob-dp",
      channelId: "ch-problems",
      authorId: "u-priya",
      createdAt: ist(24, 20, 15),
      isPinned: true,
      content: "DP transition observation from the workshop: if you only need the LIS length, the tails array plus binary search is the one to memorize. I still want juniors to write the O(n^2) dp[i] = max(dp[j] + 1) version first, so the state is obvious before the optimization.",
      problem: {
        platform: "LeetCode",
        id: "300",
        title: "Longest Increasing Subsequence",
        difficulty: "Medium",
        topic: "Dynamic Programming",
        url: "https://leetcode.com/problems/longest-increasing-subsequence/",
      },
      reactions: [
        { emoji: "💡", userIds: ["u-arjun", "u-aditya", "u-sneha", "u-saurav", "u-karan", "u-meera"] },
        { emoji: "👍", userIds: ["u-rahul", "u-ananya", "u-devansh", "u-aisha"] },
      ],
    },
    {
      ...base,
      id: "m-prob-1901",
      channelId: "ch-problems",
      authorId: "u-arjun",
      createdAt: ist(29, 18, 42),
      content: "Has anyone solved CF 1901C using greedy?\nI'm getting WA on the second test.",
      problem: {
        platform: "Codeforces",
        id: "1901C",
        title: "Add, Divide and Floor",
        difficulty: "1400",
        topic: "Greedy",
        url: "https://codeforces.com/problemset/problem/1901/C",
      },
      attachments: [
        {
          id: "a-cpp",
          name: "greedy-1901c.cpp",
          mime: "text/x-c++src",
          size: size("greedy-1901c.cpp"),
          url: "/uploads/greedy-1901c.cpp",
          kind: "code",
        },
      ],
      reactions: [
        { emoji: "👍", userIds: ["u-priya", "u-rahul", "u-aditya"] },
        { emoji: "💡", userIds: ["u-priya", "u-ananya"] },
        { emoji: "❤️", userIds: ["u-sneha"] },
      ],
    },
    {
      ...base,
      id: "m-1901-r1",
      channelId: "ch-problems",
      parentId: "m-prob-1901",
      authorId: "u-priya",
      createdAt: ist(29, 18, 46),
      content: "I think the key observation is that only the minimum and the maximum matter. The same x is applied to every element, so the gap shrinks from both ends together.",
      reactions: [{ emoji: "💡", userIds: ["u-arjun", "u-aditya", "u-rahul"] }],
    },
    {
      ...base,
      id: "m-1901-r2",
      channelId: "ch-problems",
      parentId: "m-prob-1901",
      authorId: "u-rahul",
      createdAt: ist(29, 18, 49),
      content: "Wouldn't that fail when min and max have different parity and you always append x = 0? The second sample needs a 1 or the two ends never meet.",
    },
    {
      ...base,
      id: "m-1901-r3",
      channelId: "ch-problems",
      parentId: "m-prob-1901",
      authorId: "u-arjun",
      createdAt: ist(29, 18, 52),
      content: "Ah yes, you're right. My code was appending 0 whenever the max was even.",
    },
    {
      ...base,
      id: "m-1901-r4",
      channelId: "ch-problems",
      parentId: "m-prob-1901",
      authorId: "u-priya",
      createdAt: ist(29, 18, 55),
      content: "Take x = min % 2. That pulls both ends toward the same integer. Simulate the second sample before you print the list of operations.",
      reactions: [{ emoji: "👍", userIds: ["u-arjun", "u-sneha"] }],
    },
    {
      ...base,
      id: "m-1901-r5",
      channelId: "ch-problems",
      parentId: "m-prob-1901",
      authorId: "u-aditya",
      createdAt: ist(29, 18, 58),
      content: "Also watch n = 1, and the case where everything is already equal. The answer is 0. Do not print a line of operations.",
    },
    {
      ...base,
      id: "m-1901-r6",
      channelId: "ch-problems",
      parentId: "m-prob-1901",
      authorId: "u-arjun",
      createdAt: ist(29, 19, 1),
      content: "That was the WA. I read a[1] on an array that was already equal and walked off the end. Thanks.",
    },
    {
      ...base,
      id: "m-1901-r7",
      channelId: "ch-problems",
      parentId: "m-prob-1901",
      authorId: "u-ananya",
      createdAt: ist(29, 19, 4),
      content: "If this goes into the internal set, the editorial should lead with the min/max argument. The constructive proof is shorter than the DP people try first. Print the operations only when the count is at most n.",
      reactions: [{ emoji: "🔥", userIds: ["u-rahul", "u-aditya"] }],
    },
    {
      ...base,
      id: "m-cont-poll",
      channelId: "ch-contests",
      authorId: "u-aditya",
      createdAt: ist(26, 19, 0),
      content: "",
      poll: {
        question: "Which contest should we join?",
        allowMultiple: false,
        options: [
          { id: "o-cf", text: "Codeforces Round", voterIds: ["u-arjun", "u-rahul", "u-priya", "u-aditya", "u-karan", "u-sneha", "u-meera", "u-devansh"] },
          { id: "o-cc", text: "CodeChef Starters", voterIds: ["u-ananya", "u-vikram", "u-neha", "u-rohan", "u-harsh", "u-nikhil"] },
          { id: "o-lc", text: "LeetCode Weekly", voterIds: ["u-ishaan", "u-tanvi", "u-pooja", "u-aisha"] },
        ],
      },
    },
    {
      ...base,
      id: "m-cont-edu",
      channelId: "ch-contests",
      authorId: "u-aditya",
      createdAt: ist(29, 18, 55),
      content: "Educational Round is tomorrow at 20:05 IST. I will open a virtual for anyone who misses it. The upsolve thread goes in #problem-discussion the next morning.",
      reactions: [{ emoji: "🔥", userIds: ["u-arjun", "u-sneha", "u-karan"] }],
    },
    {
      ...base,
      id: "m-icpc-roster",
      channelId: "ch-icpc",
      authorId: "u-aditya",
      createdAt: ist(28, 12, 30),
      isPinned: true,
      content: "Regionals registration opens tomorrow. Confirmed roster so far: Arjun, Sneha, and me, with Rahul as coach. If you want to challenge for a spot, the internal is on Oct 2.",
    },
    {
      ...base,
      id: "m-icpc-set",
      channelId: "ch-icpc",
      authorId: "u-priya",
      createdAt: ist(29, 16, 15),
      content: "Practice set for this week is in the zip: one graph, one DP, one greedy, two hours, one laptop. No discussion until the virtual freeze.",
      attachments: [
        {
          id: "a-zip",
          name: "icpc-practice-set.zip",
          mime: "application/zip",
          size: size("icpc-practice-set.zip"),
          url: "/uploads/icpc-practice-set.zip",
          kind: "zip",
        },
      ],
      reactions: [{ emoji: "👍", userIds: ["u-arjun", "u-aditya", "u-sneha"] }],
    },
    {
      ...base,
      id: "m-icpc-editorial",
      channelId: "ch-icpc",
      authorId: "u-rahul",
      createdAt: ist(29, 16, 40),
      content: "After the freeze, write the editorial in #problem-discussion, not only in the team chat. I want the reasoning, not just the code.",
    },
    {
      ...base,
      id: "m-res-handbook",
      channelId: "ch-resources",
      authorId: "u-rahul",
      createdAt: ist(18, 11, 0),
      isPinned: true,
      content: "Keep this next to the editor. It is the constraint table we actually use on contest nights.",
      resource: {
        kind: "pdf",
        title: "CP Handbook.pdf",
        topic: "Competitive Programming",
        size: size("cp-handbook.pdf"),
        url: "/uploads/cp-handbook.pdf",
      },
    },
    {
      ...base,
      id: "m-res-usaco",
      channelId: "ch-resources",
      authorId: "u-priya",
      createdAt: ist(19, 9, 30),
      content: "Start from the bronze graph chapter if the internal set felt random.",
      resource: {
        kind: "link",
        title: "USACO Guide",
        topic: "Algorithms",
        size: 0,
        url: "https://usaco.guide/",
      },
    },
    {
      ...base,
      id: "m-res-dp",
      channelId: "ch-resources",
      authorId: "u-arjun",
      createdAt: ist(21, 18, 20),
      content: "One page. States I forget under a timer.",
      resource: {
        kind: "pdf",
        title: "Dynamic Programming Cheatsheet.pdf",
        topic: "Dynamic Programming",
        size: size("dp-cheatsheet.pdf"),
        url: "/uploads/dp-cheatsheet.pdf",
      },
    },
    {
      ...base,
      id: "m-res-bs",
      channelId: "ch-resources",
      authorId: "u-priya",
      createdAt: ist(21, 18, 45),
      isPinned: true,
      content: "Use this when the check function is the actual problem.",
      resource: {
        kind: "pdf",
        title: "Binary Search Cheatsheet.pdf",
        topic: "Binary Search",
        size: size("binary-search-cheatsheet.pdf"),
        url: "/uploads/binary-search-cheatsheet.pdf",
      },
    },
    {
      ...base,
      id: "m-work-schedule",
      channelId: "ch-workshops",
      authorId: "u-kavita",
      createdAt: ist(22, 9, 0),
      isPinned: true,
      content: "Workshop schedule for this month: Sep 29 Python lab, Oct 6 graph basics, Oct 13 mock ICPC. Room is Lab 3 unless the notice says otherwise.",
    },
    {
      ...base,
      id: "m-work-door",
      channelId: "ch-workshops",
      authorId: "u-vikram",
      createdAt: ist(29, 15, 40),
      content: "I will be at the Lab 3 door from 4:40 PM with the attendance sheet. The practice notebook is the one pinned above.",
      reactions: [{ emoji: "👍", userIds: ["u-meera", "u-tanvi"] }],
    },
    {
      ...base,
      id: "m-work-level",
      channelId: "ch-workshops",
      authorId: "u-meera",
      createdAt: ist(29, 16, 2),
      content: "Is the Python workshop for people who already know loops, or are we starting from input and output?",
    },
    {
      ...base,
      id: "m-work-level-r1",
      channelId: "ch-workshops",
      parentId: "m-work-level",
      authorId: "u-vikram",
      createdAt: ist(29, 16, 8),
      content: "We start from input and output. If loops are already comfortable, sit towards the back and take the second notebook, the one with the list problems.",
    },
    {
      ...base,
      id: "m-dm-priya-1",
      conversationId: "dm-priya",
      authorId: "u-priya",
      createdAt: ist(28, 19, 32),
      content: "Try maintaining prefix minima while you scan from the left. The query becomes a comparison against that running value, not another loop.",
    },
    {
      ...base,
      id: "m-dm-priya-2",
      conversationId: "dm-priya",
      authorId: "u-saurav",
      createdAt: ist(28, 19, 34),
      content: "Oh, that worked. The inner loop was the TLE, not the map.",
    },
    {
      ...base,
      id: "m-dm-rahul-1",
      conversationId: "dm-rahul",
      authorId: "u-rahul",
      createdAt: ist(29, 18, 58),
      content: "Can you take the binary search doubt session on Thursday? Priya is at the workshop and the juniors already have three problems stuck on the monotone check.",
    },
    {
      ...base,
      id: "m-dm-aditya-1",
      conversationId: "dm-aditya",
      authorId: "u-aditya",
      createdAt: ist(27, 13, 10),
      content: "Internal contest draft is with Ananya. Do not share the statements outside CP Core Team.",
    },
    {
      ...base,
      id: "m-dm-aditya-2",
      conversationId: "dm-aditya",
      authorId: "u-saurav",
      createdAt: ist(27, 13, 18),
      content: "Understood. I will only review constraints.",
    },
    {
      ...base,
      id: "m-grp-icpc-1",
      conversationId: "grp-icpc",
      authorId: "u-aditya",
      createdAt: ist(29, 17, 20),
      content: "Saturday practice is 7 to 9 PM. One laptop. Arjun reads, Sneha codes the implementation, I will call out edge cases.",
    },
    {
      ...base,
      id: "m-grp-icpc-2",
      conversationId: "grp-icpc",
      authorId: "u-sneha",
      createdAt: ist(29, 17, 28),
      content: "I want the graph problem if it shows up. Last time we lost twenty minutes on the input format.",
      reactions: [{ emoji: "👍", userIds: ["u-arjun"] }],
    },
    {
      ...base,
      id: "m-grp-icpc-3",
      conversationId: "grp-icpc",
      authorId: "u-rahul",
      createdAt: ist(29, 17, 36),
      content: "Freeze at 8:40. No new submits after that unless the sample is failing.",
    },
    {
      ...base,
      id: "m-grp-core-1",
      conversationId: "grp-core",
      authorId: "u-neha",
      createdAt: ist(29, 11, 45),
      content: "Room booking for the mock ICPC is confirmed for Oct 13, Lab 3 and Lab 4.",
    },
    {
      ...base,
      id: "m-grp-core-2",
      conversationId: "grp-core",
      authorId: "u-ananya",
      createdAt: ist(29, 12, 10),
      content: "I need one more reviewer for the DP problem. The checker is ready. The statement is not.",
    },
    {
      ...base,
      id: "m-grp-core-3",
      conversationId: "grp-core",
      authorId: "u-ishaan",
      createdAt: ist(29, 12, 26),
      content: "Print the team sheets on Friday. I will bring the extra keyboards.",
      reactions: [{ emoji: "👍", userIds: ["u-neha", "u-aditya"] }],
    },
  ].map((message) => ({
    ...base,
    ...message,
  }));

  const bookmarks = [
    { id: "b-dp", userId: "u-saurav", messageId: "m-prob-dp", savedAt: ist(24, 21, 5) },
    { id: "b-bs", userId: "u-saurav", messageId: "m-res-bs", savedAt: ist(21, 19, 10) },
  ];

  const notifications = [
    {
      id: "n-saurav-overflow",
      userId: "u-saurav",
      actorId: "u-arjun",
      messageId: "m-doubt-overflow",
      channelId: "ch-doubts",
      conversationId: null,
      kind: "mention",
      text: "Arjun Mehta mentioned you in #doubts",
      createdAt: ist(29, 18, 20),
      read: false,
    },
  ];

  const caughtUp = ist(29, 19, 30);
  const reads = {};
  for (const user of users) {
    reads[user.id] = { channels: {}, conversations: {} };
    for (const channel of channels) reads[user.id].channels[channel.id] = caughtUp;
    for (const conversation of conversations) reads[user.id].conversations[conversation.id] = caughtUp;
  }
  reads["u-saurav"].channels["ch-doubts"] = ist(29, 16, 0);
  reads["u-saurav"].channels["ch-contests"] = ist(29, 12, 0);
  reads["u-saurav"].conversations["dm-rahul"] = ist(29, 12, 0);

  return {
    seedVersion: 1,
    users,
    channels,
    conversations,
    messages,
    bookmarks,
    notifications,
    reads,
    categories: ["General", "Competitive Programming", "Learning"],
  };
}

module.exports = { buildSeed, ist };
