// Theme tokens for KPH.
// globals.css only *uses* these variables (e.g. var(--surface)); the values live here so that
// light and dark can be swapped by changing <html data-theme="...">.

export type Theme = "light" | "dark";
export const defaultTheme: Theme = "light";
export const themeStorageKey = "kph-theme";

const light = {
  background: "#f6f5f1",
  surface: "#ffffff",
  "surface-muted": "#f0eee8",
  "surface-hover": "#ebe8e0",
  "surface-selected": "#e3efe8",
  header: "rgba(246, 245, 241, 0.86)",
  text: "#1c1f1d",
  "text-secondary": "#55605a",
  muted: "#7b857f",
  "icon-muted": "#8a948e",
  border: "#e3e0d8",
  "border-subtle": "#ece9e2",
  "border-strong": "#cfcabd",
  accent: "#2f6f57",
  "accent-hover": "#265a47",
  "accent-subtle": "#e3efe8",
  "accent-text": "#24604a",
  "accent-indicator": "#2f6f57",
  "on-accent": "#ffffff",
  "shadow-subtle": "rgba(28, 31, 29, 0.06)",
  "shadow-elevated": "rgba(28, 31, 29, 0.12)",
  "shadow-dialog": "rgba(28, 31, 29, 0.22)",
  overlay: "rgba(20, 24, 22, 0.45)",
  "tooltip-background": "#1c1f1d",
  "tooltip-text": "#f6f5f1",
  "selection-background": "#cfe6da",
  "selection-text": "#14241c",
  skeleton: "#ebe8e0",
  success: "#2f7d57",
  error: "#b42318",
  "chart-yellow": "#d9a441",
  "chart-rose": "#d66f7d",
  "chart-blue": "#5b8fd6",
  "number-background": "#ffffff",
  "number-text": "#1c1f1d",
  "number-border": "#e3e0d8",
  "number-shadow": "rgba(28, 31, 29, 0.08)",
  "number-secondary-background": "#f0eee8",
  "number-secondary-text": "#55605a",
  "number-secondary-border": "#e3e0d8",
  "number-secondary-shadow": "rgba(28, 31, 29, 0.05)",
  "problem-background": "#ffffff",
  "problem-border": "#e3e0d8",
  "problem-text": "#55605a",
  "problem-title": "#1c1f1d",
  "problem-tag": "#7b857f",
  "problem-footer": "#7b857f",
  "problem-accent": "#2f6f57",
  "difficulty-background": "#ece9e2",
  "difficulty-border": "#e3e0d8",
  "difficulty-text": "#55605a",
  "mark-sand-background": "#efe6d2",
  "mark-sand-text": "#7a5b22",
  "mark-sage-background": "#e0eee6",
  "mark-sage-text": "#24604a",
  "mark-rose-background": "#f5e1e3",
  "mark-rose-text": "#8f3a47",
  "mark-ink-background": "#e6e8ec",
  "mark-ink-text": "#2f3a4d",
  "mark-blue-background": "#e0eaf7",
  "mark-blue-text": "#2c5a95",
  "avatar-sage-background": "#dcebe2",
  "avatar-sage-text": "#24604a",
  "avatar-blue-background": "#dce7f6",
  "avatar-blue-text": "#2c5a95",
  "avatar-rose-background": "#f4dde0",
  "avatar-rose-text": "#8f3a47",
  "avatar-ring": "rgba(28, 31, 29, 0.08)",
};

// `typeof light` makes TypeScript complain if dark forgets a token.
const dark: typeof light = {
  background: "#121514",
  surface: "#1a1e1c",
  "surface-muted": "#202522",
  "surface-hover": "#262c29",
  "surface-selected": "#22332b",
  header: "rgba(18, 21, 20, 0.86)",
  text: "#eceee9",
  "text-secondary": "#aab3ad",
  muted: "#7f8983",
  "icon-muted": "#8b958f",
  border: "#2a302d",
  "border-subtle": "#222824",
  "border-strong": "#3a423e",
  accent: "#5fbf93",
  "accent-hover": "#74cca5",
  "accent-subtle": "#1c2e26",
  "accent-text": "#7dd3ab",
  "accent-indicator": "#5fbf93",
  "on-accent": "#0d1511",
  "shadow-subtle": "rgba(0, 0, 0, 0.3)",
  "shadow-elevated": "rgba(0, 0, 0, 0.45)",
  "shadow-dialog": "rgba(0, 0, 0, 0.6)",
  overlay: "rgba(0, 0, 0, 0.6)",
  "tooltip-background": "#eceee9",
  "tooltip-text": "#121514",
  "selection-background": "#2c4a3c",
  "selection-text": "#eceee9",
  skeleton: "#262c29",
  success: "#5fbf93",
  error: "#f0857a",
  "chart-yellow": "#e0b25a",
  "chart-rose": "#e08a97",
  "chart-blue": "#7aa7e6",
  "number-background": "#1a1e1c",
  "number-text": "#eceee9",
  "number-border": "#2a302d",
  "number-shadow": "rgba(0, 0, 0, 0.35)",
  "number-secondary-background": "#202522",
  "number-secondary-text": "#aab3ad",
  "number-secondary-border": "#2a302d",
  "number-secondary-shadow": "rgba(0, 0, 0, 0.25)",
  "problem-background": "#1a1e1c",
  "problem-border": "#2a302d",
  "problem-text": "#aab3ad",
  "problem-title": "#eceee9",
  "problem-tag": "#7f8983",
  "problem-footer": "#7f8983",
  "problem-accent": "#5fbf93",
  "difficulty-background": "#222824",
  "difficulty-border": "#2a302d",
  "difficulty-text": "#aab3ad",
  "mark-sand-background": "#33291a",
  "mark-sand-text": "#e3c886",
  "mark-sage-background": "#1c2e26",
  "mark-sage-text": "#7dd3ab",
  "mark-rose-background": "#3a2328",
  "mark-rose-text": "#eea0ac",
  "mark-ink-background": "#262b35",
  "mark-ink-text": "#b9c3d6",
  "mark-blue-background": "#1f2c40",
  "mark-blue-text": "#9bbcf0",
  "avatar-sage-background": "#23382e",
  "avatar-sage-text": "#7dd3ab",
  "avatar-blue-background": "#243449",
  "avatar-blue-text": "#9bbcf0",
  "avatar-rose-background": "#432a30",
  "avatar-rose-text": "#eea0ac",
  "avatar-ring": "rgba(255, 255, 255, 0.1)",
};

function block(theme: Theme, tokens: Record<string, string>) {
  const vars = Object.entries(tokens)
    .map(([name, value]) => `--${name}:${value};`)
    .join("");
  return `:root[data-theme="${theme}"]{color-scheme:${theme};${vars}}`;
}

// Injected into <head> as <style id="app-theme"> by layout.tsx.
export const themeStyles = block("light", light) + block("dark", dark);

// Runs in <head> before the page paints, so a saved theme never flashes the wrong colours.
export const themeInitScript = `(function(){try{var t=localStorage.getItem(${JSON.stringify(
  themeStorageKey,
)});document.documentElement.setAttribute("data-theme",t==="light"||t==="dark"?t:${JSON.stringify(
  defaultTheme,
)});}catch(e){}})();`;
